# Generated by Django 3.2.9 on 2022-03-23 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickupTime', models.DateTimeField(auto_now_add=True)),
                ('userLocation', models.CharField(default='', max_length=100)),
                ('NoOfBoxes', models.IntegerField(default=0)),
                ('recieverLocation', models.CharField(default='', max_length=100)),
                ('recievername', models.CharField(default='', max_length=100)),
                ('recieverphone', models.CharField(default='', max_length=50)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
    ]
