# Generated by Django 3.2.9 on 2022-03-23 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_shipment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='pickupTime',
            field=models.DateTimeField(),
        ),
    ]
