# Generated by Django 3.2.9 on 2022-03-24 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_remove_shipment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
