# Generated by Django 3.2.9 on 2022-03-24 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_remove_shipment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='statuses',
            field=models.CharField(choices=[('delivered', 'delivered'), ('picked', 'picked'), ('canceled', 'canceled')], default='', max_length=50),
        ),
    ]
